"""Recompute report measurements from the validated release; never hand-edit totals."""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / 'scripts')]
import config
from common import VNEDU as V, require_validated_release, load_ontology
from rdflib import Graph, URIRef
from rdflib.compare import isomorphic
from rdflib.namespace import RDF, OWL, SH, FOAF, SKOS


def main():
    require_validated_release()
    data = Graph().parse(config.DATA_TTL)
    full = Graph().parse(config.ALL_TTL)
    inferred = Graph().parse(config.RDF_DIR / 'vnedu-inferred.ttl')
    links = Graph().parse(config.LINKS_TTL)
    ontology = load_ontology()
    void = Graph().parse(config.VOID_TTL)
    expected = ontology + data + inferred + links + void
    if not isomorphic(expected, full):
        raise SystemExit('Published union does not match its source graphs')
    inst = json.loads((config.SILVER_DIR / 'institutions.json').read_text(encoding='utf-8'))
    metrics = {
        'Institutions': len(inst),
        'HEIs': len(set(full.subjects(RDF.type, V.HigherEducationInstitution))),
        'People': len(set(full.subjects(RDF.type, V.Person))),
        'Leaders': len(set(full.subjects(RDF.type, V.InstitutionLeader))),
        'Alumni': len(set(full.subjects(RDF.type, V.Alumnus))),
        'EducationParticipants': len(set(full.subjects(RDF.type, V.EducationParticipant))),
        'Observations': len(set(full.subjects(RDF.type, V.SourceObservation))),
        'Programs': len(set(full.subjects(RDF.type, V.AcademicProgram))),
        'Majors': len(set(full.subjects(RDF.type, V.Major))),
        'CurrentProvinces': len(set(full.subjects(RDF.type, V.Province))),
        'FormerProvinces': len(set(full.subjects(RDF.type, V.FormerProvince))),
        'AssertedTriples': len(data), 'InferredTriples': len(inferred), 'LinkTriples': len(links),
        'OntologyTriples': len(ontology), 'UnionTriples': len(full), 'MetadataTriples': len(void),
        'LocalResources': len({s for s in full.subjects() if isinstance(s, URIRef) and str(s).startswith(config.RES_NS)}),
        'Classes': len({s for s in ontology.subjects(RDF.type, OWL.Class) if isinstance(s, URIRef) and str(s).startswith(str(V))}),
        'ObjectProperties': len({s for s in ontology.subjects(RDF.type, OWL.ObjectProperty) if str(s).startswith(str(V))}),
        'DataProperties': len({s for s in ontology.subjects(RDF.type, OWL.DatatypeProperty) if str(s).startswith(str(V))}),
        'FoundingConflicts': len(set(data.subjects(V.reportedFoundingDate, None))),
    }
    coverage = {field: {'present': sum(bool(i.get(field)) for i in inst.values()), 'denominator': len(inst)}
                for field in ('founding_year', 'province', 'ownership', 'website', 'lat', 'students', 'admission_codes')}
    report = Graph().parse(config.REPORTS_DIR / 'shacl-report.ttl')
    severities = Counter(str(report.value(s, SH.resultSeverity)).split('#')[-1]
                         for s in report.subjects(RDF.type, SH.ValidationResult))
    metrics['Warnings'] = severities['Warning']
    metrics['Violations'] = severities['Violation']
    metrics['InformationResults'] = severities['Info']
    link_predicates = Counter(str(p) for _, p, _ in links)
    payload = {'metrics': metrics, 'coverage_all_institutions': coverage, 'link_predicates': link_predicates,
               'union_isomorphic_to_components': True,
               'note': 'Counts are local release measurements, not accuracy or national coverage estimates.'}
    (config.REPORTS_DIR / 'audit-metrics.json').write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    table_dir = ROOT / 'docs' / 'report' / 'tables'
    tex = '% Generated by audit/release_metrics.py\n'
    tex += ''.join('\\newcommand{\\metric' + key + '}{' + f'{value:,}'.replace(',', '{,}') + '}\n' for key, value in metrics.items())
    (table_dir / 'audit-metrics.tex').write_text(tex, encoding='utf-8')
    print(json.dumps(payload, indent=2))


if __name__ == '__main__':
    main()
